appname: "rideplan"
layout: "main"
charset: "UTF-8"
template: "template_toolkit"
#session: "simple" #default. in memory

engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag: '%>'
